{"name": "test_add_string__expect_exception", "status": "passed", "start": 1627243364915, "stop": 1627243364915, "uuid": "0bbd15a8-9630-4800-a2df-e9ba96a7f64d", "historyId": "0e93b819cc2e8121f7281dc8e4eaaf78", "testCaseId": "acdfa2d25acd97a898f7ad50ee211963", "fullName": "testproject.test_mymath#test_add_string__expect_exception", "labels": [{"name": "parentSuite", "value": "testproject"}, {"name": "suite", "value": "test_mymath"}, {"name": "host", "value": "Nori-PC"}, {"name": "thread", "value": "5884-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testproject.test_mymath"}]}